Race condition fix. Code format cleanup for visibility.
New _sshi_retry_task function, to allow for retrying a task. This is mostly used as a (crappy) way of coping with minor race conditions.
Re-expanded spacing and code-formatting (The 'set' command already reformats subroutines in memory. Might as well make the original readable).
Removed some unneeded stuff in __sshi_l

diff --git a/files/ssh b/files/ssh
--- a/files/ssh
+++ b/files/ssh
@@ -42,21 +42,23 @@
 # \$mb == Maximum buffer before flushing to log file.
 alias __sshi_l="perl -MIO::Handle -e '\$mb=1000;exit(1)if(!\$ARGV[0]);\$SIG{INT}=\"IGNORE\";\
  if(open(\$l,\">\",\$ARGV[0])){\$l->autoflush(1);STDOUT->autoflush(1);\
-  (\$b,\$c,\$p);while(!eof (STDIN)){\$c=getc(STDIN);print \$c;\
+  while(!eof (STDIN)){\$c=getc(STDIN);print \$c;\
    if(length(\$b)>=\$mb){print \$l \$b;\$b=undef;}\
    elsif(\$c eq \"\\r\"||\$c eq \"\\n\"){print \$l \$b;\$b=undef;}\
    \$b.=\$c;}close(\$l);}
  else{die(ord(7).ord(7).ord(7).\"Problem writing to \\\"\".\$ARGV[0].\"\\\":\".\$!.\"\\n\");}' --"
 
 #- Modification of anything within this section requires you to reread your rc or restart bash.
-ssh(){
+ssh () {
 #- Set the configuration defaults, if no global override have been set.
 # ** DO NOT MODIFY THESE DIRECTLY. THEY SHOULD BE DEFINED IN YOUR LOCAL bashrc. **
-_sshi_defaults(){ local IFS=$'\n'
- while read -r L;do
-  [[ "${L}" =~ ^[[:blank:]]*\# ]]&&continue #- Skip comment lines.
-  [[ "${L}" =~ ^[[:blank:]]*([^\ \t\=]+)[[:blank:]]*\=[[:blank:]]*(.*) ]]&&{
-   echo "[ -z \"\${${BASH_REMATCH[1]}}\" ]&&local ${BASH_REMATCH[1]}=${BASH_REMATCH[2]}";}
+_sshi_defaults () {
+ local IFS=$'\n'
+ while read -r L; do
+  [[ "${L}" =~ ^[[:blank:]]*\# ]] && continue #- Skip comment lines.
+  [[ "${L}" =~ ^[[:blank:]]*([^\ \t\=]+)[[:blank:]]*\=[[:blank:]]*(.*) ]] && {
+   echo "[ -z \"\${${BASH_REMATCH[1]}}\" ]&&local ${BASH_REMATCH[1]}=${BASH_REMATCH[2]}"
+  }
  done<<EOF
  SSHI_ADD_SUBS="sudo ssh tar addpath"
  SSHI_INC_FILES=()
@@ -78,15 +80,22 @@ EOF
 }
 
 #- Format and output local error messages.
-_sshi_err(){ local S="****************";echo -ne "${S}\n\a\a\aWARNING: ${1}${S}\n";}
+_sshi_err () {
+ local S="****************"
+ echo -ne "${S}\n\a\a\aWARNING: ${1}${S}\n"
+}
 
 #- Get SSH hostname and scan conf(s). Missing files are ignored.
-_sshi_scancnf(){
+_sshi_scancnf () {
 #- $1 is user config. $2 is main conf. Rest are SSH options.
- local CF=();local OP=()
- [ -f "${1}" ]&&CF=(${1});[ -f "${2}" ]&&CF=(${CF} ${2})
- local C=0;for O in ${*};do
-  [ ${C} -ge ${#CF[@]} ]&&OP=(${OP[@]} ${O});C=$((${C}+1))
+ local CF=()
+ local OP=()
+ [ -f "${1}" ] && CF=(${1})
+ [ -f "${2}" ] && CF=(${CF} ${2})
+ local C=0
+ for O in ${*}; do
+  [ ${C} -ge ${#CF[@]} ] && OP=(${OP[@]} ${O})
+  C=$((${C}+1))
  done
 #- SSH Command line option knowledge.
 # These are the known options for my installed OpenSSH version (v.7.2p2).
@@ -98,7 +107,7 @@ _sshi_scancnf(){
 #  -(3)- : Decouple user@ prefix.
 #  -(4)- : Only host lines
 #  -(5)- : Escape wildcard types
- cat ${CF[@]}|perl -e '
+ cat ${CF[@]} | perl -e '
   sub o{$l="local ";$r="^\\s*$_[1]";print $l.$_[0]."\n"if((!$_[1])||(grep(/$r/,@{$_[2]})));}
   $sw="^\\-[1246AaCfGgKkMNnsTtVvXxYy]";$op="^\\bcDEeFIiLlmOopQqRSWw]"; #-(1)- & -(2)-
   $sh="";while($ar=shift(@ARGV)){if($ar=~/$op/){shift(@ARGV);}elsif(!($ar=~/$sw/)){$sh=$ar;}}
@@ -116,17 +125,35 @@ _sshi_scancnf(){
 #- Clean the SSH Logs dir.
 # Removes .log files smaller than ${SSHI_LOG_MIN_SIZE} and compress .log files
 # older than ${SSHI_LOG_CMP_AGE}.
-_sshi_clean_log_dir () { local IFS=$'\n';local CT="$(date +'%s')"
- [ -z "${SSHI_LOG_COMPRESS}" ]&&{ return;};[ ${SSHI_LOG_COMPRESS} -le 0 ]&&{ return;}
- [ -z "${SSHI_LOG_CMP_AGE}" ]&&{
-  echo "SSHI_LOG_COMPRESS set, but age undefined. Cannot compress old logs."; return;}
- local F=;for F in $(find ${SSHI_LOG_LOC} -maxdepth 1 -printf "%Cs %s %p\n"|grep -e "\.log$");do
-  [[ "${F}" =~ ^([0-9]+)\ ([0-9]+)\ (.*) ]]&&{ local D="$(((${CT}-${BASH_REMATCH[1]})/86400))"
-   local S="${BASH_REMATCH[2]}";local L="${BASH_REMATCH[3]}";}
-  [ ${D} -ge ${SSHI_LOG_CMP_AGE} ]&&{
-   [ ${S} -lt ${SSHI_LOG_MIN_SIZE} ]&&{
-    echo "Removing ${L} (Size is ${S} bytes. Minimum size is ${SSHI_LOG_MIN_SIZE}).";rm ${L};}||
-   { echo "Compressing ${L}";${SSHI_LOG_CMP_BIN} ${SSHI_LOG_CMP_OPTS} ${L};} }
+_sshi_clean_log_dir () {
+ local IFS=$'\n'
+ local CT="$(date +'%s')"
+ [ -z "${SSHI_LOG_COMPRESS}" ] && {
+  return
+ }
+ [ ${SSHI_LOG_COMPRESS} -le 0 ] && {
+  return
+ }
+ [ -z "${SSHI_LOG_CMP_AGE}" ] && {
+  echo "SSHI_LOG_COMPRESS set, but age undefined. Cannot compress old logs."
+  return
+ }
+ local F=
+ for F in $(find ${SSHI_LOG_LOC} -maxdepth 1 -printf "%Cs %s %p\n"|grep -e "\.log$"); do
+  [[ "${F}" =~ ^([0-9]+)\ ([0-9]+)\ (.*) ]] && {
+   local D="$(((${CT}-${BASH_REMATCH[1]})/86400))"
+   local S="${BASH_REMATCH[2]}"
+   local L="${BASH_REMATCH[3]}"
+  }
+  [ ${D} -ge ${SSHI_LOG_CMP_AGE} ] && {
+   [ ${S} -lt ${SSHI_LOG_MIN_SIZE} ] && {
+    echo "Removing ${L} (Size is ${S} bytes. Minimum size is ${SSHI_LOG_MIN_SIZE})."
+    rm ${L}
+   } || {
+    echo "Compressing ${L}"
+    ${SSHI_LOG_CMP_BIN} ${SSHI_LOG_CMP_OPTS} ${L}
+   }
+  }
  done
 }
 
@@ -135,8 +162,8 @@ _sshi_clean_log_dir () { local IFS=$'\n';local CT="$(date +'%s')"
 #  -(1)- : $b stands for {b}rackets.
 #  -(2)- : Grab [SSHI_INCLUDE] sections in bashrc.
 #          * GETS BOTH SSH_INCLUDE AND SSHI_INCLUDE. The former will be deprecated soon.
-_sshi_getrc(){
- set|/usr/bin/perl -e '$rc=shift(@ARGV);my%addSubs;foreach my$f(@ARGV){$addSubs{$f}=1;}
+_sshi_getrc () {
+ set | /usr/bin/perl -e '$rc=shift(@ARGV);my%addSubs;foreach my$f(@ARGV){$addSubs{$f}=1;}
   my$b;foreach my$l(<STDIN>){
    if($l=~/^\s*(\S+)\s+\([^\(\)]*\)\s*$/){$b=$1;} #-(1)-
    print $l if($addSubs{$b});$b=undef if($l=~/^\}\s*([\;\#]?.*)/);}
@@ -148,18 +175,36 @@ _sshi_getrc(){
 }
 
 #- TODO: Package external files for inclusion.
-_sshi_package_include_files(){
- for I in "${SSHI_INC_FILES[@]}";do
+_sshi_package_include_files () {
+ for I in "${SSHI_INC_FILES[@]}"; do
   [[ ${I} =~ ^([^:]+):([^:]+)$ ]] && {
    echo -ne "\"${BASH_REMATCH[1]}\" "
    echo -ne "\"${BASH_REMATCH[2]}\" "
   }
-  echo "I: ${I}";
- done;
+  echo "I: ${I}"
+ done
 }
 
-#_sshi_package_include_files
-#return
+#- Retry execution of a task for a maximum number of tries, pausing every 0.1$RANDOM seconds.
+_sshi_retry_task () {
+  local OP=(${@})
+  #- MR == Max. Retries before giving up.
+  local MR=${OP[0]}
+  OP[0]=
+  local OUT=
+  local LP=1
+  local CT=0
+  while [ ${LP} -ge 1 ]; do
+   CT=$((${CT}+1))
+   eval "O=\"$(${OP[@]} 2>&1;echo "\";LP=${?}")"
+   OUT="${O}"
+   [ ${LP} -ge 1 ] && {
+    [ ${CT} -ge ${MR} ] && break
+    sleep "0.1${RANDOM}"
+   }
+  done
+  echo -e "R_O=\"${OUT}\";R_T=${LP}"
+}
 
 #- Use Perl for BASE64 encode/decode. This eliminates the need to
 # keep track of different encode/decode tools and their cmd line opts.
@@ -167,48 +212,82 @@ local S_BE="perl -MMIME::Base64 -e '\$f=join(\"\",<STDIN>);print encode_base64(\
 local S_BD="perl -MMIME::Base64 -e '\$f=join(\"\",<STDIN>);print decode_base64(\$f);'"
 
 #- Get/set SSHI variable defaults.
-eval "$(_sshi_defaults)"; eval "$(_sshi_scancnf ${SSHI_UC} ${SSHI_MC} ${@})"
+eval "$(_sshi_defaults)"
+eval "$(_sshi_scancnf ${SSHI_UC} ${SSHI_MC} ${@})"
 
 #- Log file name format.
 local S_LFM="${SSH_HOST}-$(date +'%Y-%m-%d_%H-%M-%S').log"
 #- Determine if we should log.
-[ -n "${SSHI_IS_SSH}" ]&&[ -n "${SSHI_NO_LOG_REMOTE}" ]&&{ S_NL=1;unset S_LF;}||{
+[ -n "${SSHI_IS_SSH}" ] && [ -n "${SSHI_NO_LOG_REMOTE}" ] && {
+ S_NL=1
+ unset S_LF
+} || {
 # Log by default. Turn off logging when requested.
- [ -n "${SSHI_LOG_BY_DEF}" ]&&{ [ -n "${S_NL}" ]&&unset S_LG S_NL||S_LG=1;}||{
+ [ -n "${SSHI_LOG_BY_DEF}" ] && {
+  [ -n "${S_NL}" ] && unset S_LG S_NL || S_LG=1
+ } || {
 # Do not log by default. Turn on logging when requested.
-  [ -n "${S_LG}" ]&&local S_LG=1;}
+  [ -n "${S_LG}" ] && local S_LG=1
+ }
 #- Make sure log location is writable.
- [ -n "${S_LG}" ]&&{ local S_LF="${SSHI_LOG_LOC}/${S_LFM}"
+ [ -n "${S_LG}" ] && {
+  local S_LF="${SSHI_LOG_LOC}/${S_LFM}"
  #- Create SSH log directory if needed.
-  [ -n "${SSHI_LOG_LOC}" ]&&{ [ -n ${SSHI_CREATE_LOG_LOC} ]&&{ [ ! -e ${SSHI_LOG_LOC} ]&&{
-   mkdir -p ${SSHI_LOG_LOC}||_sshi_err "Unable to create dir:\n   ${SSHI_LOG_LOC}.";} } }
-  #- Make sure log directory is writeable.
-  local S_E=
+  [ -n "${SSHI_LOG_LOC}" ] && {
+   [ -n ${SSHI_CREATE_LOG_LOC} ] && {
+    [ ! -e ${SSHI_LOG_LOC} ] && {
+     mkdir -p ${SSHI_LOG_LOC} || _sshi_err "Unable to create dir:\n   ${SSHI_LOG_LOC}."
+    }
+   }
+  }
+  #- Make sure log directory is writeable. Try twice, after pausing for a bit.
+  # The length is randomized to compensate for > 2 simultaneous SSH sessions vying for the file.
   local WT=${SSHI_LOG_LOC}/.SSHI_WRITE_OK
-  rm ${WT} 2>/dev/null||S_E=$((${S_E}+1));touch ${WT} 2>/dev/null||S_E=$((${S_E}+1))
-  [ -n "${S_E}" ]&&{
+  local S_E=0
+  local OK=
+  while [ -z "${OK}" ]; do
+   eval "$(_sshi_retry_task 2 rm ${WT})"
+   S_E=$((${S_E}+${R_T}))
+   eval "$(_sshi_retry_task 2 touch ${WT})"
+   S_E=$((${S_E}+${R_T}))
+   [ ${S_E} = 0 ] && {
+    OK=1
+   } || {
+    sleep "0.1${RANDOM}"
+   }
+  done
+  [ ${S_E} -gt 0 ] && {
    _sshi_err "Unable to write to directory '${SSHI_LOG_LOC}'.\nSession will not be logged."
-   unset S_LF;}||{ _sshi_clean_log_dir;touch ${S_LF};} } }
+   unset S_LF
+  } || {
+   _sshi_clean_log_dir
+   touch ${S_LF}
+  }
+ }
+} 
 
 #- Skip prompt and rc file shipping if requested.
-[ -n "${NOPROMPT}" ]&&unset S_F
+[ -n "${NOPROMPT}" ] && unset S_F
 #- Parse things and connect if we have a matched entry in the SSH config.
-[ -n "${S_F}" ]&&{
+[ -n "${S_F}" ] && {
  local SSHREMCMD= #- Holds contents of commands to run on remote host.
 #- PROMPTONLY set on a host .ssh/config. Set things accordingly.
- [ -n "${PROMPTONLY}" ]&&{ [ -n "${SSHI_RPS1}" ]&&{
-   echo -e "Connecting to ${S_F} with local prompt.\n";SSHREMCMD="export PS1=\"${SSHI_RPS1}\";exec bash";}
- }||{
+ [ -n "${PROMPTONLY}" ] && {
+  [ -n "${SSHI_RPS1}" ] && {
+   echo -e "Connecting to ${S_F} with local prompt.\n"
+   SSHREMCMD="export PS1=\"${SSHI_RPS1}\";exec bash"
+  }
+ } || {
  #- The rcfile to use remotely. Regenerates every time you log in.
  # local .bashrc will be called at the end. Overrides can be defined on the remote.
  # This variable is exported for use on remote systems.
-  [ -z "${RCPUSH}" ]&&RCPUSH=".bashrc_pushed-${USER}"
+  [ -z "${RCPUSH}" ] && RCPUSH=".bashrc_pushed-${USER}"
  #- Add an alias to bash (use your customized bash env).
   local USH="alias bash='/bin/bash --rcfile ~/${RCPUSH}'"
  #- Code to determine user's local RC ( ${LRC} )
   local LRC='for F in .bashrc .bash_profile .profile;do [ -e ~/${F} ]&&{ echo ${F};break;};done'
   local RBASHRC='. $('"${LRC}"');'
-  [ -n "${SSHI_RPS1}" ]&&RBASHRC+="export PS1=\"${SSHI_RPS1}\""
+  [ -n "${SSHI_RPS1}" ] && RBASHRC+="export PS1=\"${SSHI_RPS1}\""
   local RBASHRC_E
   echo -e "Connecting to ${S_F} with local shell includes.\n"
 
@@ -220,44 +299,76 @@ local S_LFM="${SSH_HOST}-$(date +'%Y-%m-%d_%H-%M-%S').log"
    echo '**** Using tee -i for logging (NO OUTPUT FILTERING). ****';echo;}"
   eval "${PC}"
  #- Gather aliases.
-  local S_A=;local OI=${IFS};IFS=$'\n';
-  for A in $(alias);do
+  local S_A=
+  local OI=${IFS}
+  IFS=$'\n'
+  for A in $(alias); do
    #- Replace the __sshi_l alias, if an old Perl version was found locally.
-   [[ "${A}" =~ ^alias\ __sshi_l ]]&&{ [ -n "${OPERL}" ]&&{ A="alias __sshi_l='tee -i'";} }
+   [[ "${A}" =~ ^alias\ __sshi_l ]] && {
+    [ -n "${OPERL}" ] && {
+     A="alias __sshi_l='tee -i'"
+    }
+   }
    S_A="${S_A}${A};"
-  done;IFS=${OI}
+  done
+  IFS=${OI}
  #- Use RCPUSH file if in an SSH session. Allows you to reuse your shipped stuff when
  # using ssh on remote systems.
  # ** This only really matters when ssh is included in SSHI_ADD_SUBS.
  # Attempt to use pushed rc if SSH. Use local rc if non-SSH
-  local RC=;[ -n "${SSHI_IS_SSH}" ]&&[ -e "~/${RCPUSH}" ]&&{ RC="~/${RCPUSH}";echo "NN: ${RC}";}||
-  { RC=~/$(eval ${LRC});}
+  local RC=
+  [ -n "${SSHI_IS_SSH}" ] && [ -e "~/${RCPUSH}" ] && {
+   RC="~/${RCPUSH}"
+   echo "NN: ${RC}"
+  } || {
+   RC=~/$(eval ${LRC})
+  }
  #- Retrieve SSHI_ADD_SUBS functions and [SSH_INCLUDE] lines.
  # Functions need to be decoded before 'source'ing them (for some reason). Decoded output is
  # piped to RCPUSH.funcs file, which is sourced from the pushed rc file.
   local RFUNCS="export RCPUSH=${RCPUSH};$(_sshi_getrc ${RC} ${SSHI_ADD_SUBS})"
   local RFUNCS_E="sleep 0.2;echo \"$(echo "${RFUNCS}"|eval ${S_BE})\"|${S_BD}>~/${RCPUSH}.funcs;. ~/${RCPUSH}.funcs"
   RBASHRC_E="export SSHI_IS_SSH=1;${S_A}${RFUNCS_E};${RBASHRC}"
-  RBASHRC_E=${RBASHRC_E//\$/\\$};RBASHRC_E=${RBASHRC_E//\"/\\\"}
+  RBASHRC_E=${RBASHRC_E//\$/\\$}
+  RBASHRC_E=${RBASHRC_E//\"/\\\"}
   local SSHREMCMD="echo \"${RBASHRC_E}\">~/${RCPUSH};exec bash --rcfile ~/${RCPUSH}"
  }
 }
 #- Compile the SSH command to run (including logging stuff) and run it.
 local LC=
 local SSHEXEC=("${SSHI_SSH_BIN}" ${@})
-[ -n "${SSHREMCMD}" ]&&SSHEXEC=(${SSHEXEC[@]} "-t" "${SSHREMCMD}")
-[ -n "${S_LF}" ]&&{ [ -z "${OPERL}" ]&&{ LC="__sshi_l ${S_LF}";}||{ LC="tee -i ${S_LF}";} }
-[ -n "${LC}" ]&&{ ${SSHEXEC[*]}|eval ${LC};}||{ ${SSHEXEC[*]};}
+[ -n "${SSHREMCMD}" ] && SSHEXEC=(${SSHEXEC[@]} "-t" "${SSHREMCMD}")
+[ -n "${S_LF}" ] && {
+ [ -z "${OPERL}" ] && {
+  LC="__sshi_l ${S_LF}"
+ } || {
+  LC="tee -i ${S_LF}"
+ }
+}
+[ -n "${LC}" ] && {
+ ${SSHEXEC[*]} | eval ${LC}
+} || {
+ ${SSHEXEC[*]}
+}
 #- Logging report.
 echo "------------------------------------------------"
-[ -n "${S_LG}" ]&&{ [ -n "${S_LF}" ]&&{
+[ -n "${S_LG}" ] && {
+ [ -n "${S_LF}" ] && {
  #- Report the log file name, if it is not zero-length. Otherwise remove the file.
  #- Report the session log path, but not if zero-length.
-  [ -s "${S_LF}" ]&&{ echo "Session logged to ${S_LF}";}||
- #- Warn the user of zero-length log, and clear the file.
-  { echo "No output logged from session. Removing ${S_LF}";rm "${S_LF}";}
+  [ -s "${S_LF}" ] && {
+   echo "Session logged to ${S_LF}"
+  } || {
+  #- Warn the user of zero-length log, and clear the file.
+   echo "No output logged from session. Removing ${S_LF}"
+   rm "${S_LF}"
+  }
  #- Warn the user that we were unable to write the session log.
- }||{ echo "WARNING: Logging is enabled, but unable to write to log. Verify SSHI_LOG_LOC is correct.";} }
+ } || {
+  echo "WARNING: Logging is enabled, but unable to write to log. Verify SSHI_LOG_LOC is correct."
+ }
+}
+
 } # END ssh
 
 # vim: filetype=sh tabstop=1 expandtab
