Added log maintenance routine to ssh.
New subroutine _clean_log_dir, removes/compresses old SSH logs.
Configuration variables:
SSHI_LOG_COMPRESS - Enable or disable SSH log maintenance. Set to 0 or '' to disable. Default is enabled (1).
SSHI_LOG_CMP_AGE  - Only perform maintenance on logs with an mtime that is xx days older. Default is 3 days.
SSHI_LOG_MIN_SIZE - Minimum size (in bytes) of SSH logs. Logs smaller than this are removed during maintenance. Default is 512 bytes.
SSHI_LOG_CMP_BIN  - Tool to use for SSH log compression. Default is 'gzip'.
SSHI_LOG_CMP_OPTS - Options to pass to compression tool. Default is '-9'.

diff --git a/files/ssh b/files/ssh
--- a/files/ssh
+++ b/files/ssh
@@ -5,6 +5,8 @@
 #
 # Source-code, documentation and revision Git repository: https://github.com/zish/bashrc_enhancements
 #
+# Author: Jeremy Melanson
+#
 # Last-Modified: 2016-09-08
 #
 # $ git clone https://github.com/zish/bashrc_enhancements
@@ -36,92 +38,98 @@
 #    You should have received a copy of the GNU Affero General Public License
 #    along with bashrc_enhancements.  If not, see <http://www.gnu.org/licenses/>.
 
-ssh () {
+ssh(){
 #-- Modification of any variables within this section requires you to restart your terminal session (or 'source' your rc file).
-
  #-- Set the configuration defaults, if no global override has been set.
- _defaults () {
-  local IFS=$'\n'; while read -r L; do
-   [[ "${L}" =~ ^[[:blank:]]*\# ]] && continue; # Skip commented-out lines.
-   [[ "${L}" =~ ^[[:blank:]]*([^\ \t\=]+)[[:blank:]]*\=[[:blank:]]*(.*) ]] && {
-    echo "[ -z \"\${${BASH_REMATCH[1]}}\" ] && local ${BASH_REMATCH[1]}=${BASH_REMATCH[2]}";
-   }
+ _defaults(){
+  local IFS=$'\n';while read -r L;do
+   [[ "${L}" =~ ^[[:blank:]]*\# ]]&&continue; #-- Skip comment lines.
+   [[ "${L}" =~ ^[[:blank:]]*([^\ \t\=]+)[[:blank:]]*\=[[:blank:]]*(.*) ]]&&{
+    echo "[ -z \"\${${BASH_REMATCH[1]}}\" ] && local ${BASH_REMATCH[1]}=${BASH_REMATCH[2]}";}
   done<<EOF
-  #-- Env Config defaults.
   SSHI_ADD_SUBS="sudo ssh tar addpath"
   SSHI_RPS1='\[\033[1;1m\](\[\033[1;31m\]SSH\[\033[0;1m\])\[\033[0;37m\]${PS1}'
   SSHI_UC=~/.ssh/config
 #  SSHI_MC=/etc/ssh/ssh_config
-  SSHI_LOG_BY_DEF=1 #TODO: Disable this when using this sub on remote SSH hosts.
+  SSHI_LOG_BY_DEF=1 #TODO: Disable this when using on remote SSH hosts.
   SSHI_LOG_LOC=~/ssh_logs
+ # Compress SSH logs by default.
+  SSHI_LOG_COMPRESS=1
+ # Comppress SSH logs older than 3 days.
+  SSHI_LOG_CMP_AGE=3
+ # Remove SSH logs smaller than 512 bytes
+  SSHI_LOG_MIN_SIZE=512
+ # Compress SSH logs using this tool:
+  SSHI_LOG_CMP_BIN=gzip
+ # Options to pass to the compression tool:
+  SSHI_LOG_CMP_OPTS=-9
 EOF
- } # END defaults ()
-
+ }
 
  #-- Get SSH hostname and scan conf(s). Missing files are ignored.
- _scancnf() {
+ _scancnf(){
   #-- $1 is user config. $2 is main conf. Rest are SSH options.
   local CF=(); local OP=()
   [ -f "${1}" ]&&CF=(${1})
   [ -f "${2}" ]&&CF=(${CF} ${2})
   local C=0; for O in ${*}; do
    [ ${C} -ge ${#CF[@]} ]&& OP=(${OP[@]} ${O})
-   C=$(( ${C} + 1 ))
+   C=$((${C} + 1))
   done
+  cat ${CF[@]}|perl -e '
   #-- SSH Command line option knowledge.
-  # These are the known options for my current version of OpenSSH (v.7.2p2):
-  # If you use another SSH tool with different options, you may be able to just set them here.
-  # ** Please let me know if you get a different version to work. I may incorporate it in
-  # ** a future version of this tool.
-  export CLISW="1246AaCfGgKkMNnsTtVvXxYy" #-- Opts that do not take an argument.
-  export CLIOPT="bcDEeFIiLlmOopQqRSWw" #-- Opts that take an argument.
-
-  cat ${CF[@]} | perl -e '
-  #-- These were defined as envvars to make things easier for others.
-  $clisw="^\\-[".$ENV{CLISW}."]";$cliopt="^\\-[".$ENV{CLIOPT}."]";
+  # These are the known options for my installed OpenSSH version (v.7.2p2).
+  $clisw="^\\-[1246AaCfGgKkMNnsTtVvXxYy]"; #-- Opts that do not take an argument.
+  $cliopt="^\\bcDEeFIiLlmOopQqRSWw]"; #-- Opts that take an argument.
   $sh="";while(my $op=shift(@ARGV)){
    if($op=~/$cliopt/){shift(@ARGV);}elsif(!($op=~/$clisw/)){$sh=$op;}}
-  #-- Decouple the user@ prefix. Output what is left.
-  $sh=~s/^\w+\@//;print "local SSH_HOST=".$sh."\n";
+  #-- Decouple user@ prefix.
+  $sh=~s/^\w+\@//;print "local SSH_HOST=$sh\n";
   while(<STDIN>){
    $p=$_;my %rgxt=("\\."=>"\\.","\\*"=>".*","\\?"=>".");
-   #-- only want host lines
-   if($p=~/^\s*host\s+([^\#]+)\#?([^\#]*)$/i){
-    $ch=$1;$a=$2;@h=($ch=~/([^\s\,]+)/g);
-    foreach $H(@h){
+   #-- Only host lines
+   if($p=~/^\s*host\s+([^\#]+)\#?([^\#]*)/i){
+    $ch=$1;$a=$2;@h=($ch=~/([^\s\,]+)/g);foreach $H(@h){
      #-- Escape wildcard types
      foreach my $e(sort{$b cmp $a}(keys(%rgxt))){$H=~s/$e/$rgxt{$e}/g;}
-      $H="^($H)\$";
-     if($sh=~/$H/){
-      print "local FOUND=".$sh."\n";
-      @O=split(/\s*\,\s*/,$a);
-      print "local LOG=1\n"if(grep(/^LOG$/,@O));
-      print "local NOLOG=1\n"if(grep(/^NOLOG$/,@O));
-      print "local NOPROMPT=1\n"if(grep(/^NOPROMPT$/,@O));
-      print "local PROMPTONLY=1\n"if(grep(/^PROMPTONLY$/,@O));
-      exit;
-  } } } }' -- ${OP[@]}
-  unset CLISW CLIOPT
- } # END _scancnf
+     $H="^($H)\$";if($sh=~/$H/){@O=split(/\s*\,\s*/,$a);
+      print "local FOUND=$sh\n";
+      print "local LOG=1\n"if(grep(/^\s*LOG$/,@O));
+      print "local NOLOG=1\n"if(grep(/^\s*NOLOG$/,@O));
+      print "local NOPROMPT=1\n"if(grep(/^\s*NOPROMPT$/,@O));
+      print "local PROMPTONLY=1\n"if(grep(/^\s*PROMPTONLY$/,@O));
+      exit;}}}}' -- ${OP[@]}
+ }
+
+ #-- Clean the SSH Logs dir.
+ _clean_log_dir (){
+  [ -z "${SSHI_LOG_COMPRESS}" ]&&{ return; }
+  [ ${SSHI_LOG_COMPRESS} -le 0 ]&&{ return; }
+  [ -z "${SSHI_LOG_CMP_AGE}" ]&&{
+   echo "SSHI_LOG_COMPRESS set, but age undefined. Cannot compress old logs."; return; }
+  for F in $(find ${SSHI_LOG_LOC} -mtime ${SSHI_LOG_CMP_AGE}|grep -v -e "\.gz$");do
+   [ $(ls -l ${F}|awk '{print $5}') -lt ${SSHI_LOG_MIN_SIZE} ]&&{ echo "Removing ${F}";rm ${F}; }||
+   { echo "Compressing ${F}";${SSHI_LOG_CMP_BIN} ${SSHI_LOG_CMP_OPTS} ${F}; }
+  done
+ }
 
  #-- Pull requested functions defined by SSHI_ADD_SUBS.
- _getrc () {
-  set|/usr/bin/perl -e '
-   $rc=shift(@ARGV);my %addSubs;
-   foreach my $f(@ARGV){$addSubs{$f} = 1;}
+ _getrc (){
+  set|/usr/bin/perl -e '$rc=shift(@ARGV);my %addSubs;
+   foreach my $f(@ARGV){$addSubs{$f}=1;}
    my $b;foreach my $l(<STDIN>){
     #-- $b stands for {b}rackets, and makes sure to record whole functions.
     if($l=~/^\s*(\S+)\s+\([^\(\)]*\)\s*$/){$b=$1;}
     print $l if($addSubs{$b});
     $b=undef if($l=~/^\}\s*([\;\#]?.*)/);}
-   my $rcFh;open($rcFh,"<",$rc)||die("Cannot open rc file $rc: ".$!);
+   my $rcFh;open($rcFh,"<",$rc)||die("Cannot open rc file $rc: $!");
    my @rc=<$rcFh>;close($rcFh);
    #-- Grab sections of bashrc marked by [SSH_INCLUDE] remarks.
    my ($i,$c,$incPos);
    foreach my $l(@rc){
     if($l=~/^\s*\#\s*\[SSH_INCLUDE\]\s+(\d+)/){$i=$1;}
     if($i){if($c<=$i){print$l;$c++;}else{$c=0;$i=0;}}}' -- ${@}
- } # END _getrc
+ }
 
  eval "$(_defaults)"
  eval "$(_scancnf ${SSHI_UC} ${SSHI_MC} ${@})"
@@ -130,7 +138,7 @@ EOF
  local LOGFMT="${SSH_HOST}-$(date +%Y-%m-%d_%H-%M-%S).log"
  #-- Determine if we should be logging.
  # Log by default. Turn off logging when requested.
- [ -n "${SSHI_LOG_BY_DEF}" ]&&{ [ -n "${NOLOG}" ]&& unset LOG NOLOG || LOG=1;}||
+ [ -n "${SSHI_LOG_BY_DEF}" ]&&{ [ -n "${NOLOG}" ]&& unset LOG NOLOG||LOG=1;}||
  # Do not log by default. Turn on logging when requested.
  { [ -n "${LOG}" ]&& local LOG=1;}
  #-- Make sure log  location is writable.
@@ -141,22 +149,17 @@ EOF
    echo "****************"
    echo -e "WARNING: Unable to write to file:\n   ${LOGFILE}.\nSession will not be logged."
    echo -e "****************\n"
-   unset LOGFILE;
- } }
-
+   unset LOGFILE;}||{ _clean_log_dir; }
+ }
  #-- Skip prompt and rc file shipping if requested.
  [ -n "${NOPROMPT}" ]&& unset FOUND;
-
  #-- Parse things and connect if we have a matched entry in the SSH config.
  [ -n "${FOUND}" ]&&{
-
   local SSHREMCMD= #-- SSH Remote command to execute for the session.
   #-- We can specify PROMPTONLY on a host in .ssh/config. Set things accordingly.
   [ -n "${PROMPTONLY}" ]&&{
-   [ -n "${SSHI_RPS1}" ]&& {
-    echo -e "Connecting to ${FOUND} with local prompt.\n"
-    SSHREMCMD="export PS1=\"${SSHI_RPS1}\";exec bash"
-   }
+   [ -n "${SSHI_RPS1}" ]&&{
+    echo -e "Connecting to ${FOUND} with local prompt.\n";SSHREMCMD="export PS1=\"${SSHI_RPS1}\";exec bash";}
   }||{
    #-- The rcfile to use remotely. Regenerates every time you log in.
    # bashrc will be called at the end. Overrides can be defined on the remote.
@@ -173,8 +176,8 @@ EOF
    #-- Default base64 encode and decode commands for different platforms.
    local B64_E=;local B64_D=;local UN=;local PL=
    local PF='UN=$(which uname);[ -n "${UN}" ]&&{ [ -x ${UN} ]&&{ PL=$(${UN} -a);
-    [[ ${PL} =~ ^Darwin ]]&&{ B64_E="base64 -i -";B64_D="base64 -D -i -";};
-    [[ ${PL} =~ ^Linux|Cygwin ]]&&{ B64_E="base64 -w 0";B64_D="base64 -di";} } }'
+   [[ ${PL} =~ ^Darwin ]]&&{ B64_E="base64 -i -";B64_D="base64 -D -i -";};
+   [[ ${PL} =~ ^Linux|Cygwin ]]&&{ B64_E="base64 -w 0";B64_D="base64 -di";} } }'
    eval "${PF}"
    #-- Gather aliases.
    local ALI=;local OI=${IFS};IFS=$'\n';for A in $(alias);do ALI="${ALI}${A};";done;IFS=${OI}
@@ -192,15 +195,11 @@ EOF
    local RFUNCS_E="sleep 0.2;echo "$(echo "${RFUNCS}"|${B64_E})"|\${B64_D}>~/${RCPUSH}.funcs;. ~/${RCPUSH}.funcs"
    RBASHRC_E="${PF};${ALI}${RFUNCS_E};${RBASHRC}"
    RBASHRC_E=${RBASHRC_E//\$/\\$};RBASHRC_E=${RBASHRC_E//\"/\\\"}
-   local SSHREMCMD="echo \"${RBASHRC_E}\">~/${RCPUSH};exec bash --rcfile ~/${RCPUSH}"
-  }
+   local SSHREMCMD="echo \"${RBASHRC_E}\">~/${RCPUSH};exec bash --rcfile ~/${RCPUSH}";}
   [ -n "${LOGFILE}" ]&&{ /usr/bin/ssh ${@} -t "${SSHREMCMD}"|tee -i ${LOGFILE};}||
   { /usr/bin/ssh ${@} -t "${SSHREMCMD}";}
- }||{
-  #-- No match found in config. Just run SSH command.
-  [ -n "${LOGFILE}" ]&&{ /usr/bin/ssh ${@}|tee -i ${LOGFILE};}||{ /usr/bin/ssh ${@};}
- }
-
+ #-- No match found in config. Just run SSH command.
+ }||{ [ -n "${LOGFILE}" ]&&{ /usr/bin/ssh ${@}|tee -i ${LOGFILE};}||{ /usr/bin/ssh ${@};} }
  #-- Logging report.
  echo "------------------------------------------------"
  [ -n "${LOG}" ]&&{
@@ -208,7 +207,7 @@ EOF
    #-- Report the log file name, if it is not zero-length. Otherwise remove the file.
    [ -s "${LOGFILE}" ]&&{ echo "Session logged to ${LOGFILE}";}||
    { echo "No output logged from session. Removing ${LOGFILE}"; rm "${LOGFILE}";}
-  }||{
-   echo "WARNING: Logging is enabled, but unable to write to log. Verify  SSHI_LOG_LOC is correct.";
- } }
+  }||{ echo "WARNING: Logging is enabled, but unable to write to log. Verify  SSHI_LOG_LOC is correct.";} }
 } # END ssh
+
+# vim: filetype=sh
